#ifndef CORE_ERROR_H
#define CORE_ERROR_H

typedef enum core_error
{
	CORE_ERROR_NONE = 0,
	CORE_ERROR_UNKNOWN_INTERFACE = -1,
	CORE_ERROR_CREATE_WINDOW = -2,
	CORE_ERROR_OUT_OF_MEMORY = -3,
	CORE_ERROR_INIT_RENDERER = -4,
	CORE_ERROR_NO_RENDERER_BACKEND = -5,
	CORE_ERROR_OPEN_CONSOLE = -6,
	CORE_ERROR_ALREADY_EXISTS = -7,
	CORE_ERROR_OPERATION_FAILED = -8,
	CORE_ERROR_INVALID_ARGUMENT = -9,
	CORE_ERROR_FILE_NOT_FOUND = -10,
	CORE_ERROR_FILE_READ = -11,
	CORE_ERROR_FILE_WRITE = -12,
	CORE_ERROR_UNKNOWN = -1000
} core_error;

#endif // CORE_ERROR_H
